# Generated by Django 4.1.3 on 2022-12-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='destination',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
