# Generated by Django 4.1.3 on 2022-12-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
