# Generated by Django 4.1.3 on 2023-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Children',
            new_name='children',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
