# Generated by Django 4.1.3 on 2023-02-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_children_booking_children_remove_user_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='checkin',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tourpackage',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
