# Generated by Django 4.1.3 on 2023-02-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_mobile_booking_checkin_booking_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='destination',
        ),
    ]
