# Generated by Django 4.1.3 on 2023-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_user_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tourpackage',
            new_name='packagename',
        ),
    ]
