# Generated by Django 4.1.3 on 2023-02-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_tourpackage_booking_packagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkout',
        ),
    ]
