# Generated by Django 4.1.3 on 2023-02-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_booking_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkin',
            new_name='checkindate',
        ),
    ]
