# Generated by Django 4.1.3 on 2023-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_rename_checkin_booking_checkindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkoutdate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
