# Generated by Django 4.1.3 on 2023-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_rename_checkoutdate_booking_checkout1date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
