# Generated by Django 4.1.3 on 2023-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prise',
            field=models.CharField(default=23, max_length=225),
            preserve_default=False,
        ),
    ]
