# Generated by Django 4.1.3 on 2023-02-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_rename_checkout1date_booking_checkoutdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='prise',
        ),
    ]
