# Generated by Django 4.1.3 on 2023-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_booking_prise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
