# Generated by Django 4.1.3 on 2023-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
