# Generated by Django 4.1.3 on 2023-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('Discription', models.CharField(max_length=500)),
                ('DateOfStart', models.DateField(max_length=225)),
                ('Prise', models.CharField(max_length=225)),
                ('ListOfPlace', models.CharField(max_length=225)),
                ('Totalseet', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='package/')),
            ],
        ),
    ]
