# Generated by Django 4.1.3 on 2023-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_rename_contact_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
