# Generated by Django 4.1.3 on 2023-02-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='ListOfPlace',
            new_name='Days',
        ),
    ]
